#!/bin/bash

#VERSION 003

THISDIR="$(dirname "$0")"

LD_LIBRARY_PATH=$THISDIR/program:$LD_LIBRARY_PATH

#/home/<user name>/.config/libreoffice/4/user   (LibreOffice 4 & 5)

if [ ! -d $HOME/.config/lo/4/user ] ; then
  mkdir -p $HOME/.config/lo/4/user
  cp -av $THISDIR/CONFIG/* $HOME/.config/lo/4/user/
fi

$THISDIR/program/soffice --norestore --nologo $@
