" System vimrc file for MacVim
"
" Maintainer:	Bjorn Winckler <bjorn.winckler@gmail.com>
" Last Change:	Sat Aug 29 2009

set nocompatible

" The default for 'backspace' is very confusing to new users, so change it to a
" more sensible value.  Add "set backspace&" to your ~/.vimrc to reset it.
set backspace+=indent,eol,start

" Disable localized menus for now since only some items are translated (e.g.
" the entire MacVim menu is set up in a nib file which currently only is
" translated to English).
set langmenu=none

" Python2
" MacVim uses Homebrew python2 if installed, otherwise configured one
if exists("&pythondll") && exists("&pythonhome")
  if filereadable("/usr/local/Frameworks/Python.framework/Versions/2.7/Python")
    " Homebrew python 2.7
    set pythondll=/usr/local/Frameworks/Python.framework/Versions/2.7/Python
    set pythonhome=/usr/local/Frameworks/Python.framework/Versions/2.7
  endif
endif

" Python3
" MacVim uses Homebrew python3 if installed, next try to use python.org binary
if exists("&pythonthreedll") && exists("&pythonthreehome") &&
      \ !filereadable(&pythonthreedll)
  if filereadable("/Library/Frameworks/Python.framework/Versions/3.5/Python")
    " https://www.python.org/downloads/mac-osx/
    set pythonthreedll=/Library/Frameworks/Python.framework/Versions/3.5/Python
    set pythonthreehome=/Library/Frameworks/Python.framework/Versions/3.5
  endif
endif



set fileencoding=utf-8
set encoding=utf-8

if has('gui_running')
    set lines=999 columns=999
endif



" http://vim.wikia.com/wiki/Get_the_name_of_the_current_file
set encoding=utf-8
set nowrap
set noswapfile
set nobackup

"izaci sa esc
nmap <ESC> :macaction terminate:<CR>
nmap <C-P> :execute "!$VIMRUNTIME/../../../../../ptxt " . substitute(expand('%:p'), '.conv.txt', '', 'y') . " /p"<CR>

set guifont=Monaco:h14
