#!/bin/bash

# 008 VERSION

# MacVim.app/Contents/Resources/vim/vimrc

FNAME="$(cd "$(dirname "$1")"; pwd)/$(basename "$1")"

#https://stackoverflow.com/questions/6121091/get-file-directory-path-from-file-path
F18_EDITOR_DIR=$(dirname $0)

#echo $F18_EDITOR_DIR, $FNAME

#https://github.com/knowhow/T0_knowhow/blob/fdee93923fa49838deb1c2c398c9b4/sed/f18_editor_mac#L12
cat $FNAME | iconv -c -f IBM852 -t UTF-8 | sed -e 's/#%[0-9A-Z_]\{5\}#//g' > $FNAME.conv.txt

open -a $F18_EDITOR_DIR/MacVim.app/Contents/MacOS/MacVim $FNAME.conv.txt
