#!/bin/bash

# MacVim.app/Contents/Resources/vim/vimrc

FNAME="$(cd "$(dirname "$1")"; pwd)/$(basename "$1")"

#https://stackoverflow.com/questions/6121091/get-file-directory-path-from-file-path
F18_EDITOR_DIR=$(dirname $0)

echo $F18_EDITOR_DIR, $FNAME

cat $FNAME | sed -e "s/#\S\+#//g" | iconv -c -f IBM852 -t UTF-8 > "$FNAME.conv.txt"

#VIM_OPTS="-c ':set encoding=utf-8' -c ':set nowrap' -c ':set noswapfile' -c ':set nobackup'"
#VIM_OPTS="$VIM_OPTS' -c 'nmap <C-P> :exe '!ptxt substitute(@%%, '.conv.txt', '', 'y') /p'<CR>'"

# http://vim.wikia.com/wiki/Get_the_name_of_the_current_file
# VIM_OPTS+=' -c "nmap <C-P> :exe '!ptxt \"' . expand expand('%:p') . '\" /p'<CR>"'

echo $FNAME.conv.txt

$F18_EDITOR_DIR/MacVim.app/Contents/MacOS/MacVim $FNAME.conv.txt &
